import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { type Metadata } from "next";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { cn } from "@/lib/utils";
import {
  AppConfigBar,
  AppConfigBarWrapper,
} from "@/components/parts/appConfigBar";
import { CombinedProvider } from "@/components/providers/combinedProvider";
import { Toaster } from "@/components/uiKit/sonner";
import { BodyContentWrapper } from "@/components/parts/bodyContentWrapper";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <CombinedProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, maximum-scale=1"
          />
        </head>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          <ReactQueryDevtools
            initialIsOpen={false}
            buttonPosition="bottom-left"
          />

          <BodyContentWrapper>
            <AppConfigBarWrapper>
              <AppConfigBar />
            </AppConfigBarWrapper>
            {children}
            <Toaster />
          </BodyContentWrapper>
        </body>
      </html>
    </CombinedProvider>
  );
};

export default RootLayout;
