import "@repo/ui-kit/globals.css";
import { Inter as FontSans } from "next/font/google";
import { type Metadata } from "next";
import { cn } from "@repo/ui-kit/utils";
import {
  AppConfigBar,
  AppConfigBarWrapper,
  BodyContentWrapper,
} from "@repo/ui-blocks/parts";
import {
  CombinedProvider,
  ReactQueryDevtoolsProvider,
} from "@repo/ui-blocks/providers";
import { Toaster } from "@repo/ui-kit/sonner";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <CombinedProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, maximum-scale=1"
          />
        </head>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          <ReactQueryDevtoolsProvider>
            <BodyContentWrapper>
              <AppConfigBarWrapper>
                <AppConfigBar />
              </AppConfigBarWrapper>
              {children}
              <Toaster />
            </BodyContentWrapper>
          </ReactQueryDevtoolsProvider>
        </body>
      </html>
    </CombinedProvider>
  );
};

export default RootLayout;
