import { type Metadata } from "next";
import { type ReactNode } from "react";
import { ParticipantsList, ParticipantsListWrapper } from "@/components/parts/participantsList";
import { EventStreamProvider } from "@/components/providers/eventStreamProvider";
import { MetaSessionManager } from "@/components/parts/metaSessionManager";
import { RoomSplitView } from "@/components/parts/roomSplitView";
import { CurrentRoomProvider } from "@/modules/room/hooks/useCurrentRoom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RoomLayoutProps = {
  children: ReactNode;
  params: Promise<{ roomId: string[] }>;
};

const RoomLayout = async (props: RoomLayoutProps) => {
  const params = await props.params;

  const { children } = props;

  const roomId = params?.roomId?.[0] ?? "";
  if (!roomId) return null;
  return (
    <CurrentRoomProvider roomId={roomId}>
      <MetaSessionManager>
        <EventStreamProvider>
          <ParticipantsListWrapper>
            <ParticipantsList />
          </ParticipantsListWrapper>
          <RoomSplitView>{children}</RoomSplitView>
        </EventStreamProvider>
      </MetaSessionManager>
    </CurrentRoomProvider>
  );
};

export default RoomLayout;
