import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";
import { type Metadata } from "next";
import dynamic from "next/dynamic";
import { cn } from "@/lib/utils";
import { AppConfigBar, AppConfigBarWrapper } from "@/components/parts/appConfigBar";
import { CombinedProvider } from "@/components/providers/combinedProvider";
import { Toaster } from "@/components/uiKit/sonner";
import { BodyContentWrapper } from "@/components/parts/bodyContentWrapper";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DynamicReactQueryDevtools = dynamic(
  () => import("@tanstack/react-query-devtools").then((mod) => mod.ReactQueryDevtools),
  {
    loading: () => null,
    ssr: false,
  },
);

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <CombinedProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        </head>
        <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
          <DynamicReactQueryDevtools initialIsOpen={false} />

          <BodyContentWrapper>
            <AppConfigBarWrapper>
              <AppConfigBar />
            </AppConfigBarWrapper>
            {children}
            <Toaster />
          </BodyContentWrapper>
        </body>
      </html>
    </CombinedProvider>
  );
};

export default RootLayout;
