import { Button } from "@/components/uiKit/button";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div>
        <Button>Generated by create next app</Button>
      </div>
    </main>
  );
}
