name: Pull request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Validate
    uses: ./.github/workflows/reusable-validate.yml
    permissions:
      contents: read # Required by checkout
      pull-requests: write # Required to add a comment to the PR
